name: Build Site (PR check)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs: 
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install deps
      run: |
        sudo apt-get -y update && \
        sudo apt-get -y install python3-tornado python3-yaml python3-markdown python3-dateutil python3-nbconvert pandoc

    - name: Build site
      env:
        COURSE_RESOURCES_CSV_URL: https://docs.google.com/spreadsheets/d/e/2PACX-1vRcrLDHvgcPt1pwnPWyf3glaEr7rrdHh6RWyX7sTlD1oBMNhYCk2e0tjbYp3bc8w18pdQp7tvp2tczt/pub?gid=1486073670&single=true&output=csv
      run: |
        mkdir -p static/csv
        curl -L -s "$COURSE_RESOURCES_CSV_URL" -o static/csv/resources.csv
        make clean && make build

    # No deploy in PR validation workflow
